### ISSUE TITLE
Option to not group by region

### ISSUE THREAD

**Issue by KingTut1762** [code4recovery/pdf#1]
How can I get the PDF schedule to print chronologically instead of by City?

**Comment by joshreisner** [comment]
hi @KingTut1762 is this still something that you're interested in? here's what your schedule looks like currently (with default settings): [western-slope-d-22.pdf](https://github.com/code4recovery/pdf/files/7471398/western-slope-d-22.pdf)

making this change would mean that meetings would still be grouped by day, but would no longer have sub-groupings of Cameron Park, Coloma, Diamond Springs, etc.

**Comment by joshreisner** [comment]
here's what it would look like without the region groupings: [western-slope-no-region.pdf](https://github.com/code4recovery/pdf/files/7471435/western-slope-no-region.pdf)

**Comment by KingTut1762** [comment]
Brilliant!! Our eternal gratitude for making this happen as it contributes greatly to our goal of maintaining support for the newcomer as well as our established members. You are real heroes!!
