### ISSUE TITLE
Allow (some) Populated Fields except null data

### ISSUE THREAD

**Issue by CCFAAWebmaster** [code4recovery/pdf#16]
Hello and thanks so much for the PDF Meeting Generator. Well done thanks times 10.

I realize we have alot of (meeting) fields and must chose what are relevant to a printed meeting guide. That stated:

1) Can we customize output fields? Ex. If a meeting has "website", or if a meeting has "location notes".

2) If yes, can we assume restriction to no output where field is null? Ex. If a meeting does not have a "website" or does not have "location notes".

Super appreciative here in Sacramento.

**Comment by joshreisner** [comment]
Hey Pete, I'm open to the idea of adding more fields. i think that websites are a little weird since it's an analog format, and i'm a little wary about adding notes fields, because they are free-form multi-line. 

But we can try it out. Could you tell me what Sac's paper size is going to be? It's going to be a lot of pages right, you have like 1000 meetings or so?

**Comment by CCFAAWebmaster** [comment]
Thanks for your time and commitment Josh.

IF CCFAA elects to use the PDF Generator (still weighing our production options) we will use Width = 4.25, Height = 11.

My mockup is here = https://drive.google.com/file/d/1qEd4UmiDsy3pH3zOf2_2FgPiBce9Wzkk/view?usp=sharing

Just want to insure that if field is null, no output. TY

My best as always

**Comment by CCFAAWebmaster** [comment]
Spoke to CCF Office Manager, added request in a similar manner excluding null field.

Fields:
Notes
Location Notes

and 

I am aware than the following enhancement is in place 
[Can we include Zoom Info? #2](https://github.com/code4recovery/pdf/issues/2)

Fields: 
Conference URL	
Conference URL Notes

**Comment by joshreisner** [comment]
hey Pete, sure we can add an option to display non null notes fields. 

we won't be adding online meetings to it though

**Comment by CCFAAWebmaster** [comment]
CCF requires the online meeting details.
I'll slog thru Google plugins for a sheet to doc merge tool, else they'll use MS Publisher.

Very much appreciate the assist, this can be closed (for now ;)

**Comment by CCFAAWebmaster** [comment]
Thanks as always for the forward looking application(s) and tech support.

**Comment by joshreisner** [comment]
Ok sounds good, thanks!
