### ISSUE TITLE
Generated PDF is not including a specific region

### ISSUE THREAD

**Issue by KingTut1762** [code4recovery/pdf#18]
Greetings Heroes,

I hope you can help with an issue regarding a difference between the basic pdf meeting schedule and the new generated pdf option.
Our website url is:  https://westernsloped22.org/
It opens to the Home page and under 
**New! 
Printer Friendly Meeting Schedule**
are links to the basic pdf schedules available to our visitors.

All of the basic pdf schedules include all specific street address related meetings and relevant regions. It excludes the online only meetings which is most preferable as it helps immensely with creating a personalized printed schedule for our fellowships and groups. 
The new TSML 3.12 plugin generated pdf excludes the online only meetings (again, most preferable) as well. The problem is that one region (Pollock Pines) consisting of 9 meeting entries is excluded:
[directory.D22_12-16-2021_day region.pdf](https://github.com/code4recovery/pdf/files/7728712/directory.D22_12-16-2021_day.region.pdf)

Below is a filtered look at the 9 meetings not included in the generated pdf:
https://westernsloped22.org/meetings/?tsml-day=any&tsml-region=pollock-pines

I have checked the region entries and I find nothing different except that the Address column for those 9 entries is "Pollock Pines Recreation Park". The Region column entries appear correct as "Pollock Pines". All other meetings have a physical street address.

I've researched varied solutions but I don't know how to proceed without identifying the issue.

Any guidance would be hugely appreciated!

Thank you,
KingTut

**Comment by joshreisner** [comment]
Thanks for the report @KingTut1762 - try it again, hopefully those meetings will show up now. If not, please let us know.

**Comment by KingTut1762** [comment]
Wow that's super fast service!! Well done!! Thank you, thank you, thank you, thank you, thank you, thank you, and thanks again!
