### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by petermixt** [code4recovery/pdf#19]
Of 4 sites I have running 12 Step Meeting List.

1. One of the two CMA sites running 12 Step Meeting List on the same server running the same permissions... one gets a 500 error.
2. This also happens on one of two other CMA site on GoDaddy. Identical installs though on different servers... one gets a 500 error.
3.  Another GoDaddy install for AA works fine.

![Screenshot 2021-12-22 at 06-25-52 Server Error](https://user-images.githubusercontent.com/38595503/147107894-dba083d3-d67f-4f8c-91ab-f74dae1d80b4.png)

All permissions are 755 - All have sharing OPEN
This occurs on both Firefox and Chrome latest browsers Windows 11

Thoughts?

Pete S.

**Comment by joshreisner** [comment]
hi pete, please send the json urls that arent working and we’ll figure it out, thanks

**Comment by joshreisner** [comment]
oops never mind, checking the logs I do see the issue…

**Comment by joshreisner** [comment]
i made a [change](https://github.com/code4recovery/pdf/commit/b6763867b069602f0f3feebb009642e4f84ccf6f) that i think should fix it, please try it again and let me know if it's still not working

**Comment by petermixt** [comment]
And yes Sir it did...  All of them now function properly.
**Happy Holidays**  :)
