### ISSUE TITLE
Change to format of meeting information

### ISSUE THREAD

**Issue by WoodieFL** [code4recovery/pdf#20]
We are trying to cut down on the number of pages for our meeting list PDF. Currently, it is 55 pages and we are charged by our printer for the number of pages. We would like to print our meeting list in 5.5 x 8.5, which we can do. However, because the meeting name, location, and address are on three lines, it takes up a lot of room. What we would like to do is have the location and address all on one line, separated by a space. Below is a sample of how we would like it to look. 

What are your suggestions for accomplishing this?
![Page snippet](https://user-images.githubusercontent.com/73310072/149385353-653d43a9-4958-4546-996a-f0ee32d28db7.png)

**Comment by joshreisner** [comment]
hi @WoodieFL - sure, is this what you're looking for?

[aapinellas.pdf](https://github.com/code4recovery/pdf/files/7865629/aapinellas.pdf)

looks like it would knock your list from 55 pages down to 42.

**Comment by WoodieFL** [comment]
Yes, Josh - that's exactly what we would need!! How would I get that every
time I want to print it as we are planning to print one every month.

By the way, you are awesome!

Woodie Sayles
(727) 642-5372
***@***.***  =^..^=

**Comment by joshreisner** [comment]
Thanks!

I've made this the default behavior now for the app. If anyone complains I'll add separate lines back as an option.

**Comment by WoodieFL** [comment]
Thank you so much for doing this. You are really awesome!
