### ISSUE TITLE
A Request (make page numbers an option) and a Bug (12&12 isn't showing up) 

### ISSUE THREAD

**Issue by alangrady** [code4recovery/pdf#21]
I love what you have done to this plugin...  PDF Generator. 🕺

Request:  Make the Page the Numbers (Start #) be an option.  I import the generator meeting schedule into a InDesign document, so it would make things a bit easier on my end.

Bug:  Meeting mark with "12 Steps and 12 Traditions" aren't showing on the generator Meeting Guide... Meeting Types Legend and next to the meeting... 

Here is example.
https://markuphero.com/share/CczYpmOeD1RUPVWjzufD

https://markuphero.com/share/sRePLUp1YhZf34NG2Ecc

**Comment by joshreisner** [comment]
Ah, thanks for the bug report.

So the page numbers request, if you leave Start # blank the page numbers shouldn't show up at all?

**Comment by alangrady** [comment]
I tried that... :)

https://markuphero.com/share/Q8qYjkPG56KD58NGRxFU

**Comment by joshreisner** [comment]
sorry i was just confirming that's what you wanted. i can make it work

**Comment by joshreisner** [comment]
ok you should be good to go now 👍

**Comment by alangrady** [comment]
YES! you rock! 🕺
