### ISSUE TITLE
[Feature Request]: PDF sorted in Region, Day order

### ISSUE THREAD

**Issue by WoodieFL** [code4recovery/pdf#24]
The original half-page layout created a PDF in Region, Day order. However, we need a PDF with a page size of 5.5 x 8.5 and when we use the new Generate PDF, the only two sorting options are Day, Region or Day. It would be perfect for us if it had the Region, Day option as well. Is there any way to do this or could it be added to the Generate PDF page as an option?

I tried using Chris T's plugin, but it didn't give me the layout I need unfortunately.

**Comment by joshreisner** [comment]
hi @WoodieFL give it a try now, there's a new 'group by' option

**Comment by WoodieFL** [comment]
Josh,

You are so awesome! This worked perfectly and is just what we needed.

Of course now, someone wants the region printed at the top of each page,
which will make it easier to know what region you're looking at when
thumbing through the book. If this is too much of a pain, I will do it
manually after the PDF is created.

Thank you again for your super speedy response and great coding skills! We
really appreciate you.

**Comment by joshreisner** [comment]
thanks @WoodieFL ! i know what they're asking and i wish i knew a way to do it. i can repeat a header across the whole document, but not one at the section level. this would be useful when grouping by region as well as day, e.g. 

1. Sunday
2. Sunday, contd.
3. Sunday, contd.
4. Monday
5. Monday, contd.

etc. I'm going to close this issue but rest assured if I figure that out I'll add it to all the PDF views.

**Comment by WoodieFL** [comment]
I appreciate your help and will pass along your comments to my committee.

Woodie Sayles
(727) 642-5372
***@***.***  =^..^=

**Comment by WoodieFL** [comment]
I just thought of something that might help you figure out how to print the
Region or Day at the top of each page. The old 4x7 format printed by region
and it had the region at the top of each page. Could you look at the code
for that one and perhaps integrate it into the new one?

It's attached here in case that will help you. Thanks for your help again.

Woodie Sayles
(727) 642-5372
***@***.***  =^..^=
