### ISSUE TITLE
Add Tooltips / Advice on Numbering & Other Columns

### ISSUE THREAD

**Issue by lloy0076** [code4recovery/pdf#25]
If you omit the page start number, you don't get page numbers; but this is not mentioned anywhere and you either find it out by accident or read the code.

Other fields might benefit from tooltips/help.

[Yes I'm willing to submit a PR for this but not quite yet].

**Comment by lloy0076** [comment]
... although my i18n to Spanish/French might be non-idiomatic when I do (I can read both languages at a very basic level and will see any obvious bad translations but I don't have the nuance of a Spanish/French/Quebecois person to understand the subtleties).

**Comment by joshreisner** [comment]
i agree the detail about the page numbers is not easy to discover, i can add some kind of help text. no need to make a PR
