### ISSUE TITLE
PDF Printable Meeting List Customizations

### ISSUE THREAD

**Issue by D51WebAdmin** [code4recovery/pdf#29]
Thank you for your service with coding and all that goes into the 12 Step Meeting List. I recently discovered the new PDF service that you are all working on and I am very novice when it comes to managing websites and really don’t have any idea how to write code so please take what I say with a grain of salt since I am ignorant on most of this. 

Pre pandemic the website admin for District 51 in Illinois had put together a Word doc for a printable meeting list which many of the long-timers in the district appreciated. However when I became the main point of contact in January in 2020 being able to keep up with a printable list whilst getting used to the ropes of managing the website and making it more user friendly was definitely a challenge. By May of 2020 I pulled the printable meeting list off of our website (aadistrict51.org) because it was impossible at the time to put out something that was accurate. This now brings me to today where I discovered the new PDF generator which is so unbelievably useful and I’m very grateful for all of your work on it. A request/suggestion that I had would be able to modify the column count in the PDF generator to add 2, 3, or even 4 columns in order to create a slightly more compact version of the meeting list for an 8.5” x 11” or even legal size paper (8.5” x 14”). See attached document of how we had created the old meeting list as a reference. This would make creating a tri-fold meeting list easier which would save greatly on printing costs, and time. Unfortunately I have no idea how to write code for this otherwise I would have and then submitted it to be able to contribute. ☹ If you know of any work arounds I would greatly appreciate any suggestions you have.

**Comment by joshreisner** [comment]
hi @D51WebAdmin 

i dont see an example uploaded

did you see our section about [booklet printing](https://github.com/code4recovery/pdf#booklet-printing) in the readme?

another option is a new service called [updf](https://updf.com/print-pdf/print-pdf-as-booklet/) 

if you’re looking for a column approach on wordpress you might try [this plugin](https://wordpress.org/plugins/12-step-meeting-pdf-generator/)
