### ISSUE TITLE
Trouble opening the PDF 

### ISSUE THREAD

**Issue by JenniferWallis** [code4recovery/pdf#31]
"Data is protected. If you are using 12 Step Meeting List, consider setting data sharing to open."
I saw that others had this issue and the resolution was to go to the settings under Data, but I do not see that option.
Maybe I am just in over my head as usual:)

**Comment by joshreisner** [comment]
That's correct, go to Wordpress Dashboard > Meetings > Import & Settings > Feed Management > Feed Sharing and set `Restricted` to `Open`.

![feed-security](https://user-images.githubusercontent.com/1551689/207518636-b5209417-7b0c-4b7c-bea6-0774798fae03.png)

For what it's worth, I think it's time to get rid of this setting.
