### ISSUE TITLE
Reduce line spacing to generate fewer pages and reducing printing costs

### ISSUE THREAD

**Issue by meetings03** [code4recovery/pdf#33]
Is it possible to reduce the line spacing between the region name and first line of the first meeting listed for that region, the last line of the last meeting listed in a region and the next region, and the space between each meeting listing within a region by around 50%.
We have over 2800 meetings in our TSML and when generating a pdf for our print version the current line spacing generates 148 pages for a 5.5 x 8.5 pdf for print. by reducing the line spacing, we could save around 25% or 35-40 pages. This would greatly reduce the printing costs for us and for anyone utilizing the pdf generator to make printed lists of any size.
I have attached a pdf to help show as an example.
[Less Space Example.pdf](https://github.com/code4recovery/pdf/files/10935413/Less.Space.Example.pdf)

**Comment by meetings03** [comment]
Josh,
Any space savings will help a lot.
It looks like if you reduce the space between the region name and the 
last meeting entry of each region, it will gain even more space.
Maybe give that a try and see where we're at.

Thank You for being of service,
Greg S.
Area 03 Meeting List Coordinator

**Comment by meetings03** [comment]
Josh,
As a followup, I've attached a pdf that I went ahead and did a manual 
estimated line space reduction for the whole page and it looks like it 
can save around 25%, +or-. Every little bit will help over the course of 
140+ pages.

Thank You for being of service,
Greg S.
Area 03 Meeting List Coordinator

**Comment by joshreisner** [comment]
attachments over email dont get uploaded to github 😦 can you upload on the website?

**Comment by meetings03** [comment]
Here's the example pdf
[Less Space Condensed.pdf](https://github.com/code4recovery/pdf/files/10944870/Less.Space.Condensed.pdf)

**Comment by joshreisner** [comment]
ok, i've reduced the margins now. you're down to from 148 to 126

* [before-148.pdf](https://github.com/code4recovery/pdf/files/10947727/before-148.pdf)
* [after-126.pdf](https://github.com/code4recovery/pdf/files/10947726/after-126.pdf)

**Comment by meetings03** [comment]
I'm getting the 500 server error again when trying to generate a pdf?

Thank You for being of service,
Greg S.
Area 03 Meeting List Coordinator

**Comment by joshreisner** [comment]
looks like it's working for other feeds but throwing a fast 500 on your feed. i'm not seeing anything in sentry (where it normally reports errors)

i'll try to look at it tonight to see if i can learn anything. if not i'll create a new issue
