### ISSUE TITLE
The Meeting Legends are bunching up together on the directory.pdf export

### ISSUE THREAD

**Issue by alangrady** [code4recovery/pdf#34]
My printer pointed this issue last week. 😢 😄

https://capture.dropbox.com/dKpu02AtUISaenzO

![image](https://user-images.githubusercontent.com/6485723/227959584-1c4209ca-3b03-430e-b982-7fb1ed8ac33d.png)

**Comment by joshreisner** [comment]
oops thanks give it another try now

**Comment by alangrady** [comment]
🕺 SUCCESS! Thanks!
