### ISSUE TITLE
issue loading json

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/pdf#4]
Not being able to contact a developer is always an issue when updates are needed.
I''m looking forward to using your new PDF generator when it works.  
My JSON file is correct and open independently on my browser... but returns an error as I have posted as a bug.
Here is a screen shot of what I get.
![Screenshot 2021-10-03 at 17-27-43 PDF Generator](https://user-images.githubusercontent.com/38595503/135780142-7cd62136-1b85-4a25-9409-5389b6473fa5.png)

Thank you,
Pete S.
PeterMixt

_Originally posted by @petermixt in https://github.com/code4recovery/12-step-meeting-list/discussions/548#discussioncomment-1422298_

**Comment by tech2serve** [comment]
@petermixt, Please confirm if updating the website certificate solved this problem?

Please reference [this comment](https://github.com/code4recovery/12-step-meeting-list/issues/544#issuecomment-933072764)

**Comment by petermixt** [comment]
> @petermixt, Please confirm if updating the website certificate solved this problem?
> 
> See [this comment](https://github.com/code4recovery/12-step-meeting-list/issues/544#issuecomment-933072764)

Confirmed problem solved.
