### ISSUE TITLE
Error on dev site - SSL certificate problem

### ISSUE THREAD

**Issue by onemooresam** [code4recovery/pdf#43]
Error:
Could not fetch data. Please check the address. Received the following message: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://averym8.sg-host.com/wp-admin/admin-ajax.php?action=meetings&nonce=f8def5b229

Updating atlantaaa.org's site on a dev site (https://averym8.sg-host.com/) to migrate them from the customized TSML plugin they stopped updating in Spring 2020. A printed meeting list is desired. Can this be made to work on the dev site?

**Comment by anchovie91471** [comment]
Hey @onemooresam, I'm not seeing any errors in our logs on [pdf.code4recovery.org](https://pdf.code4recovery.org/).

Did you click the button on the Import/Export page (shown here)?
<img width="428" alt="Screen Shot 2023-06-18 at 11 02 21 AM" src="https://github.com/code4recovery/pdf/assets/9162021/90ab7573-30e4-4696-9fda-8fc7cecdaf82">

As long as you have a feed that's available from the dev site, you can print a list. Do you have a feed setup on the settings page of 12 Step Meeting List (on dev)?

**Comment by onemooresam** [comment]
Hi there, 

I just tried again. On the dev site, in Meetings>>Import & Export, I click the "Generate PDF" button. That opens a new window at https://pdf.code4recovery.org/?json=https%3A%2F%2Faverym8.sg-host.com%2Fwp-admin%2Fadmin-ajax.php%3Faction%3Dmeetings%26nonce%3D9e9de4f759. Accepting the defaults and clicking the Generate button yields, "Could not fetch data. Please check the address. Received the following message: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://averym8.sg-host.com/wp-admin/admin-ajax.php?action=meetings&nonce=9e9de4f759"
<img width="1401" alt="dev site" src="https://github.com/code4recovery/pdf/assets/17989539/22956b1c-b6df-4635-b319-5aad53b5034c">
<img width="714" alt="C4R PDF page" src="https://github.com/code4recovery/pdf/assets/17989539/c358af9f-be3c-4918-94ed-ba35074f2fc8">

**Comment by joshreisner** [comment]
thanks sam, looks like the SSL certificate is "not trusted in all browsers" https://www.sslshopper.com/ssl-checker.html#hostname=https://averym8.sg-host.com/

@anchovie91471 i would try disabling ssl verification on our end:

on this line: https://github.com/code4recovery/pdf/blob/main/app/Http/Controllers/Controller.php#LL167C25-L167C34

add withOptions: https://laravel.com/docs/10.x/http-client#guzzle-options

verify => false https://docs.guzzlephp.org/en/stable/request-options.html#verify

`Http::withOptions(['verify' => false])->get(`

i don't think we're too worried about man-in-the-middle attacks here 😉

**Comment by joshreisner** [comment]
hi sam, you should be able to use the PDF generator with your feed now

**Comment by onemooresam** [comment]
Worked perfectly! Thank you so much!
