### ISSUE TITLE
Feature Request.

### ISSUE THREAD

**Issue by dougie-wougie** [code4recovery/pdf#47]
I would like https://pdf.code4recovery.org/ to add a checkbox and code to eliminate the page breaks between the days. This would save us a few sheets of page with each printing. 

doug

**Comment by dougie-wougie** [comment]
Did I post this in the wrong spot? It has not been seen with no comment.

**Comment by dougie-wougie** [comment]
Hi, I liked to get the feature. Is it on the roadmap?

**Comment by anchovie91471** [comment]
This is next on the list. I'll be looking into it in the coming week. Sorry for the delay in answering you.

**Comment by anchovie91471** [comment]
@dougie-wougie We just merged this feature into PDF. You should see a checkbox now that removes pagebreaks.

**Comment by dougie-wougie** [comment]
Thank you.

I just looked at https://pdf.code4recovery.org/ and did not see the enhancement. I will recheck in a bit, if the change is being pushed.

D

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by anchovie91471** [comment]
Should be updated now.
