### ISSUE TITLE
Trouble genrate a PDF from the PDF generator

### ISSUE THREAD

**Issue by ncsandiego** [code4recovery/pdf#57]
This is the link which comes up empty when I click generate PDF.
https://ncsandiegoaa.org/wp-admin/edit.php?post_type=tsml_meeting&page=generate_pdf

We use a trifold layout on a 8.5X11 size paper. We have produced our meeting directory before from the PDF generator.

**Comment by joshreisner** [comment]
doesn't sound like our plugin. could it be this one? https://wordpress.org/plugins/12-step-meeting-pdf-generator/

**Comment by ncsandiego** [comment]
Is code4recovery/pdf a plugin for generating a meeting schedule?

Liz

**Comment by joshreisner** [comment]
it is not, it's a web service at https://pdf.code4recovery.org which can print a PDF meeting schedule, but it does not support trifold layouts

the reason i wrote "doesn't sound like our plugin" is it looks like you published a link to a plugin on your website that we don't manage called "12 Step Meeting PDF"

**Comment by ncsandiego** [comment]
Actually it is PDF Generator.

Liz Hanson

**Comment by anchovie91471** [comment]
Hey Liz, Anthony B here. I’m one of the other maintainers of the PDF service. 

The plugin you have is written by a different author and isn’t related to the Code4Recovery team, so the link Josh posted is where you should post any questions or issues you’re experiencing

Code4Recovery’s PDF is similar in function but, as Josh mentioned, doesn’t offer tri-fold as a layout option.
