### ISSUE TITLE
Translate meeting types legend

### ISSUE THREAD

**Issue by anchovie91471** [code4recovery/pdf#60]
Meeting types legend is output in English, regardless of language chosen.

**Comment by anchovie91471** [comment]
@Hiro-Toko

I am working on enabling Japanese translation for this service and need a Japanese meeting feed (json, like what would be used for tsml-ui). Would you have a public one I could use to ensure things work properly?

**Comment by Hiro-Tokyo** [comment]
@anchovie91471 


Thank you for reaching me out.

Please explain more detail for this.
Like this? This is like a part of guideline for Japanese service entity and members.

https://lavish-wedge-66e.notion.site/86858694221542abb72ee4743933ff60?v=bddd79da42b2408c95e8bf3919915477&pvs=4

**Comment by anchovie91471** [comment]
@Hiro-Tokyo, I apologize, I thought I had responded.

This was very helpful in working on fully translating the PDF generator.

In the next update, All the text in the PDF should now generate in Japanese. I appreciate your help with it!
