### ISSUE TITLE
Meeting List Download - 500 Error

### ISSUE THREAD

**Issue by anchovie91471** [code4recovery/pdf#63]
### Discussed in https://github.com/code4recovery/pdf/discussions/62

<div type='discussions-op-text'>

<sup>Originally posted by **ATLCOTech** February  1, 2024</sup>
Hi All - we are trying to download the Meeting List for Atlanta and am getting an server error 500. 

![image](https://github.com/code4recovery/12-step-meeting-list/assets/147879274/c667ed27-2fd5-406a-8ec5-c0f95185b464)
</div>

**Comment by joshreisner** [comment]
(we raised the PHP `memory_limit` on the server from 128M to 256M to accommodate a large list of meetings)
