### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by dougie-wougie** [code4recovery/pdf#80]
I get a 500 server error when selecting Group by -> Day. If I choose another option, it will work fine. 

d

**Comment by dougie-wougie** [comment]
https://aascv.org/wp-admin/admin-ajax.php?action=meetings

[CleanShot 2024-09-10 at 07.58.28.png]

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by dougie-wougie** [comment]
Have you been able to replicate the issue?

**Comment by anchovie91471** [comment]
@dougie-wougie, sorry man. I've been traveling for a few days and have had limited access to my computer. I will test this out as soon as I possibly can. Sorry for the delay.

**Comment by dougie-wougie** [comment]
I would like this solved. I want to issue the 4th quarter update.

**Comment by anchovie91471** [comment]
Please tell me (or put a screenshot here) what the options you are using on the PDF generator. The defaults are generating the PDF for me.

**Comment by anchovie91471** [comment]
This should be fixed now.

**Comment by dougie-wougie** [comment]
Thank you for the fix! You are awesome. 

d
