### ISSUE TITLE
Filter regions included in PDF report

### ISSUE THREAD

**Issue by TerryA60** [code4recovery/pdf#84]
Our current PDF report includes all of eastern Missouri. We would like to filter this down to sub-regions to create local meeting guides. I am thinking of the ability to upload a list of regions to include in the report. A multi select box would be awkward because of the large number of regions to include or exclude. We would also like to be able to filter out online only meetings.

**Comment by anchovie91471** [comment]
PDF does not include online meetings. We are discussing, internally, the possibility of adding those to PDF, but you should not be getting any listed in a PDF from the service.

Let me do a bit of research on the filtering part and I'll get back to you.

I'm also going to convert this to a discussion until this turns into something actionable. 

Stay tuned!
