### ISSUE TITLE
PDF Generation by Users

### ISSUE THREAD

**Issue by ckyoga** [code4recovery/pdf#86]
Hello,
I understand the process to generate a PDF and then upload that file to your Wordpress site for users to download.

We would like the users to have a button where they could select the button and dynamically generate a PDF of the meetings so that any recent updates are included in the newest download.

Is this possible?

best,
Caroline

**Comment by anchovie91471** [comment]
Hey Caroline!

The PDF generator s meant as a service for trusted servants who manage meetings. Unfortunately, the amount of compute it would require to generate PDF's on the fly for the general public would simply be too cost prohibitive for us to incur.

All Code4Recovery projects, including PDF, are open source. You are always free to copy the code and set up your own PDF server if you'd like.

Thanks!
Anthony B.
